# ===============================
# 🚀 Travel Management System - Frontend Deployment Workflow
# Framework: React (Vite)
# Deployment: GitHub Pages
# Backend: Spring Boot (http://localhost:8081)
# ===============================

name: Deploy Travel Management System Frontend

on:
  push:
    branches: [ master ]     # Runs when you push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (Vite requires Node 18+)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Vite project
      - name: Build project
        run: npm run build
        env:
          # Backend API base URL
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      # Step 5: Upload production build artifact
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Step 6: Deploy built site to GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
